### ISSUE TITLE
Confirmation popup

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/conda-manager#1]
Right now the confirmation popup is divided in 4 parts, similar to conda command line interface. Most of the time the same package appear in multiple sections. I think it doesn't work well with a gui, I would expect a table indicating for each package what action will be performed (uninstall, unlink, download...).

This is a relocation of https://github.com/spyder-ide/spyder/issues/2133

(BTW, what happened to your "Working on this from next week!" ? :p )

**Comment by goanpeca** [comment]
I did work, that does not mean I finished! haha

Shit happens :sweat_smile: ?

**Comment by goanpeca** [comment]
@Nodd In the case of packages being removed, what would you expect... 

For instance lets say we install numpy 1.7 and remove 1.6

You would like to see

```
Numpy 1.6 (unlink)
Numpy 1.7 (download, extract, link)
```

And in the case of multiple packages? always list first the ones to unlink? or on after the other?

```
package 1.1
package 1.2
papa 1.6
papa 1.7
```

or ?

**Comment by Nodd** [comment]
How about a table ? Something like:

| Name | unlink | link | download | extract |
| --- | --- | --- | --- | --- |
| Numpy | 1.6 | 1.7 | 1.7 | 1.7 |
| Foo | 0.6 |  |  |  |
| Bar |  | 2.8 | 2.8 | 2.8 |

The best would be to indicate the number of bytes to download if the information is available.

**Comment by goanpeca** [comment]
Good idea :), yes the size info is available.

As soon as I finish this one I will test your plugins PR, did you manage to fix the error you got?

**Comment by Nodd** [comment]
Not yet, but I think having different spyder versions installed is a bit problematic (since `spyderplugins` in master is not a namespace plugin).

**Comment by goanpeca** [comment]
This is almost ready @Nodd :p

![conda](https://cloud.githubusercontent.com/assets/3627835/9838247/64e92870-5a1e-11e5-9271-7117c570a093.png)

The download column should have the size... (or be hidden when no package is going to be downloaded.) almost there...!

**Comment by Nodd** [comment]
Gorgeous !
Looks like there is lots of space on left and right, is it from your theme ?

**Comment by goanpeca** [comment]
Hmmm good point, I will check :p

**Comment by goanpeca** [comment]
@nodd ... finally!!

Pushing soon :-)

![image](https://cloud.githubusercontent.com/assets/3627835/12468427/8516ba38-bfb1-11e5-9fa5-e77c8cdfb845.png)

**Comment by ccordoba12** [comment]
Nice!!

**Comment by Nodd** [comment]
Beautiful ! Better than in my dreams ! :smile:
