### ISSUE TITLE
Display available versions on right click

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/conda-manager#11]

**Comment by Nodd** [comment]
Be aware that some packages have lots of versions. If there is something else in the right clic menu, put the versions in a submenu.

**Comment by goanpeca** [comment]
agreed. but for now only rigt clicking on the version column will display the other versions

**Comment by goanpeca** [comment]
Fixed by 17b8a670efcbbe8363176ba52b967b6b748766d9
