### ISSUE TITLE
Add channel support by name and by URL

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/conda-manager#18]
This has been implemented as a fade out dialog

![image](https://cloud.githubusercontent.com/assets/3627835/12485012/de2af0de-c02a-11e5-9665-0b049fc7bad6.png)

@Discalced51, made a proposal like this one, like a "palette"
![image](https://cloud.githubusercontent.com/assets/3627835/12485031/f2460590-c02a-11e5-99d9-309692979a0b.png)

@ccordoba12, @martindurant, any thoughts?

**Comment by martindurant** [comment]
I like the former solution, doesn't crowd the space unless required. In practice, I don't imagine people changing channels very often.

**Comment by ccordoba12** [comment]
I also like the first option too :-)
