### ISSUE TITLE
Plan for public release

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/conda-manager#26]
@goanpeca, what's your plan for releasing Conda manager to the general public?

One thing I think we shouldn't do (at least for a first release) is uploading packages to PyPi. I doesn't make much sense to me.

**Comment by goanpeca** [comment]
Uploading packages to pypi ?? ?

**Comment by ccordoba12** [comment]
You mention in the Readme that you can install conda-manager with `pip`, and there's also a badge about current conda-manager version on PyPi. So I assumed you wanted to pursue that route too (and even more so now that you added pip support to it ;-)

If that's not the case, then any reference to make conda-manager pip installable should be removed before next release.

---

Ok, but discounting that, what's your plan for it? My main questions are:
1. What should be conda-manager next version? I'd say **1.0** because most of what we want from it is already implemented.
2. When is this planned to be released? I'd say as soon as PR #25 is merged, to not keep adding new (extra?) features.

**Comment by goanpeca** [comment]
Ahhh ... well the pip package is doable. I have the instructions and it seems to work, so I see no harm there?

Are you happy with the current state of it (functionality-wise?)

**Comment by Nodd** [comment]
It can not be used as a plugin in spyder before 3.0 is out, maybe you want to take that into account. But since it works standalone teh releases can still be independent.

**Comment by goanpeca** [comment]
@Nodd can you test it a bit on standalone mode and make any issues relevant to it ? probably I need to hook all the create remove clone enviornments actions.

**Comment by Nodd** [comment]
Well...

``` python
Traceback (most recent call last):
  File "c:\anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda\Scripts\condamanager.exe\__main__.py", line 5, in <module>
  File "c:\anaconda\lib\site-packages\conda_manager\__init__.py", line 13, in <module>
    from conda_manager import app, data, models, utils, widgets  # analysis:ignore
  File "c:\anaconda\lib\site-packages\conda_manager\app\__init__.py", line 12, in <module>
    from .main import main               # analysis:ignore
  File "c:\anaconda\lib\site-packages\conda_manager\app\main.py", line 17, in <module>
    from conda_manager.widgets.main_window import MainWindow
  File "c:\anaconda\lib\site-packages\conda_manager\widgets\main_window.py", line 25, in <module>
    from conda_manager.widgets.packages import CondaPackagesWidget
  File "c:\anaconda\lib\site-packages\conda_manager\widgets\packages.py", line 36, in <module>
    from conda_manager.widgets.table import CondaPackagesTable
  File "c:\anaconda\lib\site-packages\conda_manager\widgets\table.py", line 18, in <module>
    from qtpy import PYQT5
ImportError: cannot import name PYQT5
```

I don't have PyQt5 installed.

Edit: OK, the qtpy version on pypi is too old, I'll retry with master branch

**Comment by ccordoba12** [comment]
@Nodd, do you have the latest `qtpy`, i.e. its master branch?

If you're using Anaconda, you can install it with

```
conda install -c spyder-ide qtpy
```

**Comment by Nodd** [comment]
At first I just used the pypi version, but it works with the master branch. I edited my previous message but it looks like it was too late !
Thanks for the conda command, it's easier than having a local repo to update.
