### ISSUE TITLE
Closing spyder while installing packages

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/conda-manager#3]
Steps to reproduce:
1. Install some package
2. Close spyder while the installation is running

There should at least be a "are you sure ?" kind of warning when closing spyder. I didn't have the time to check if the installation continued correctly in the background, but if it is not the case it can potentially break anaconda.

Relocated from https://github.com/spyder-ide/spyder/issues/2131

**Comment by goanpeca** [comment]
Fixed by 17b8a670efcbbe8363176ba52b967b6b748766d9
