### ISSUE TITLE
Slow start

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/conda-manager#37]
I profiled the startup with `python -m cProfile conda-manager.py`, and closing the window as soon as it appears. It takes 42s to boot !
Here is the result: https://gist.github.com/Nodd/6a30d6a51d2cdd9d3a02
Notice that a few lines have a cumsum time a little above 40s.

I think that the problem comes from not being able to connect to the remote server because the proxy is not taken into account. But the window should show up anyway as soon as possible. Maybe add a QCoreApplication.processEvents() somewhere before auto-updating on startup ?

I created this issue from #34 to better track it.

**Comment by goanpeca** [comment]
Well lets try something. 

1.) Can you turn off your internet and see what happens on start? (I still need to check offline mode! will do this weekend)
2.) There is info and error logging in a file at `~/.condamanager/logs/condamanager.log` can you check for ERROR messages?

**Comment by goanpeca** [comment]
@nodd I guess you have your proxy settings configured on the `.condarc` file?

Anaconda client, which seems to be the one stuck, is based on **requests** (like conda) which uses env variables to configure the proxy... something like

```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

Anaconda-client, Unlike conda it does not use settings in `.condarc` file

**Comment by Nodd** [comment]
Here is the log:
[condamanager.txt](https://github.com/spyder-ide/conda-manager/files/175797/condamanager.txt)

Yes, I configured the proxy in `.condarc`. I thought that on windows request would take the proxy value configured in the system.

I tried to set the env variables by it didn't change anything. Maybe I did something wrong because I'm on windows.

**Comment by Nodd** [comment]
It now starts within 1 second. You just disabled the update on startup, right ? I think it's better that way, yumex (the interface for yum on centos) updated every time and it's a pain.

**Comment by aperep** [comment]
Could you specify how to disable the update on startup, please?
