### ISSUE TITLE
Merge install/remove columns

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/conda-manager#4]
There are currently two separate columns for isntall and remove. These actions are mutually exclusive, so they could be merged into one to gain some horizontal space and lower the interface clutter. The different icons with different colors sould be more thn enough to distinguish between the two actions.

Relocated from https://github.com/spyder-ide/spyder/issues/2130

**Comment by goanpeca** [comment]
Done :-)  @Nodd 

![image](https://cloud.githubusercontent.com/assets/3627835/7865291/c334530c-0567-11e5-8405-7e0df5f83596.png)

**Comment by Nodd** [comment]
Nice !
`llvmmath` is not installable on your screenshot ?

**Comment by goanpeca** [comment]
Hmmm i am on win with python 32 bits so maybe is that, have not checked!
