### ISSUE TITLE
Conda manager doesn't have the right icon on the Windows taskbar

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/conda-manager#59]
I just installed conda-manager with conda. On windows (I didn't check on Linux), it has the same icon as spyder, is it normal ? I would expect a different icon for the standalone application.

**Comment by ccordoba12** [comment]
> is it normal?

No, but the fix is very simple :-)

**Comment by ccordoba12** [comment]
I'll do it.

**Comment by goanpeca** [comment]
@ccordoba12 I would like to get this in the release for this coming Thursday 14th of April
