### ISSUE TITLE
Left click on upgrade icon

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/conda-manager#67]
To mark a package to update, my first try was to left-click on the blue up arrow, byt it does nothing.
I see 2 solution:
1. A left click on the version column of an upgradeable package should mark the package to be upgraded to the mosts recent version (without dislaying the menu)
2. Change the up arrow icon so that it looks less like a button, and more like a simple arrow.

**Comment by goanpeca** [comment]
Yes, @Nodd I agree, I did not manage to make the icon change on time for the [release](https://docs.continuum.io/anaconda/navigator).

Will apply option #2

**Comment by goanpeca** [comment]
Although I actually like option # 1.

@Discalced51 what do you think, you had some concerns when I raised this?. Being able to click on the Update arrow that appears when updates are available and having the package marked for Update. Of course the arrow icon in Navigator does not convey the push me message, but it could.
