### ISSUE TITLE
Idea: merge mark for update and choose version submenu

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/conda-manager#69]
I don't know if itt's feasible with qt, but the idea is that the version submenu should be displayed when hovering the update entry. Clicking on the update entry would still mark the last version to be installed.

I'm not sure that it's discoverable enough or even if it's really useful in practice. You decide !

**Comment by goanpeca** [comment]
@Nodd, probably through some hacking, but it is not standard Qt behaviour and not standard UI behaviour, so :-1:.
