### ISSUE TITLE
Poor visuals in OS X

### ISSUE THREAD

**Issue by martindurant** [spyder-ide/conda-manager#7]
On mac osx, icons and text do not fit
![image](https://cloud.githubusercontent.com/assets/6042212/12118391/2693c8b2-b394-11e5-850e-22b8e8b23dd6.png)

**Comment by ccordoba12** [comment]
@goanpeca, it seems you customized things for the Linux case only :-)

Related question: could we use `qtawesome` for the icons?

**Comment by goanpeca** [comment]
@martindurant can you please check if this is fixed in the latest master?

I made some changes that might have fixed the issue.

**Comment by goanpeca** [comment]
@martindurant?

**Comment by martindurant** [comment]
I have branch master up to date with remote, and the problem persists.
I also needed to make some changes (const.CREATE) which were assumed by the calling code but weren't implemented - perhaps you haven't committed everything?

**Comment by goanpeca** [comment]
i did some cleanup and might have forgotten about some places will fix now.

hmmm i will have ro look further into it the.
