### ISSUE TITLE
Include pip packages in packages listing via icon

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/conda-manager#9]

**Comment by ccordoba12** [comment]
But only for _installed_ packages with `pip`, right?

**Comment by goanpeca** [comment]
Yes only installed.

I already did this and I am pushing soon, but wanted to keep track of the features.

It looks like this now :-), the remove button for `pip` packages (python logo) now displays a message saying that the feature is not (yet) implemented. I am working on a pip-api-q (akin to the conda-api-q)

![image](https://cloud.githubusercontent.com/assets/3627835/12222238/f4057984-b78c-11e5-903d-9942436fafef.png)

**Comment by ccordoba12** [comment]
Fantastic! This is going to be a terrific addition to Spyder too!

**Comment by Nodd** [comment]
Are you really able to remove them or the icon is just for show ?
Anyway, great addition ! How do you handle pip-installed packages that are available on conda ? It can easily happen when more packages are added to conda.

**Comment by goanpeca** [comment]
right now the icon displays a not yet implemented message box but i will include the funxctionality

**Comment by goanpeca** [comment]
@nodd..., if they have the exact same name, the pip package (if installed) will be displayed and the conda package will not. After removing the pip package the conda package will appear on the list. This is the option I considered the most natural so far (I have to make sure it is working like this though)

**Comment by goanpeca** [comment]
Fixed by 17b8a670efcbbe8363176ba52b967b6b748766d9
